import type { Lesson } from "@vocabulary/utils";

export const foodLesson: Lesson = {
  id: "food-fr-en",
  slug: "food",
  title: "Nourriture & Cuisine",
  description: "Apprends le vocabulaire de la nourriture et de la cuisine",
  targetLanguage: "fr",
  nativeLanguage: "en",
  cards: [
    {
      id: "food-01",
      targetWord: "mange",
      sentence: "Je ____ des pâtes tous les jours.",
      translation: "I eat pasta every day.",
      nativeWord: "eat",
      hint: "verb, 1st person singular, present",
      wordType: "verb",
    },
    {
      id: "food-02",
      targetWord: "boire",
      sentence: "On devrait ____ au moins deux litres d'eau par jour.",
      translation: "We should drink at least two litres of water a day.",
      nativeWord: "drink",
      hint: "verb, infinitive",
      wordType: "verb",
    },
    {
      id: "food-03",
      targetWord: "farine",
      sentence: "La recette demande deux tasses de ____.",
      translation: "The recipe calls for two cups of flour.",
      nativeWord: "flour",
      hint: "noun, feminine",
      wordType: "noun",
    },
    {
      id: "food-04",
      targetWord: "cuire",
      sentence: "Laisser ____ à feu doux pendant vingt minutes.",
      translation: "Let it cook on low heat for twenty minutes.",
      nativeWord: "cook",
      hint: "verb, infinitive",
      wordType: "verb",
    },
    {
      id: "food-05",
      targetWord: "savoureux",
      sentence: "Ce plat est vraiment ____.",
      translation: "This dish is really tasty.",
      nativeWord: "tasty",
      hint: "adjective, masculine singular",
      wordType: "adjective",
    },
    {
      id: "food-06",
      targetWord: "légumes",
      sentence: "Elle achète des ____ frais au marché.",
      translation: "She buys fresh vegetables at the market.",
      nativeWord: "vegetables",
      hint: "noun, masculine plural",
      wordType: "noun",
    },
    {
      id: "food-07",
      targetWord: "recette",
      sentence: "Tu as suivi la ____ à la lettre.",
      translation: "You followed the recipe to the letter.",
      nativeWord: "recipe",
      hint: "noun, feminine",
      wordType: "noun",
    },
    {
      id: "food-08",
      targetWord: "couteau",
      sentence: "Utilise un ____ bien aiguisé pour émincer les oignons.",
      translation: "Use a sharp knife to slice the onions.",
      nativeWord: "knife",
      hint: "noun, masculine",
      wordType: "noun",
    },
  ],
};
