import type { Lesson } from "@vocabulary/utils";

export const roadLesson: Lesson = {
  id: "road-code-fr-en",
  slug: "road-code",
  title: "Code de la route",
  description: "Apprends le vocabulaire de la conduite et du code de la route",
  targetLanguage: "fr",
  nativeLanguage: "en",
  cards: [
    {
      id: "road-01",
      targetWord: "conduire",
      sentence: "Il apprend à ____ depuis trois mois.",
      translation: "He has been learning to drive for three months.",
      nativeWord: "drive",
      hint: "verb, infinitive",
      wordType: "verb",
    },
    {
      id: "road-02",
      targetWord: "ceinture",
      sentence: "Attache ta ____ de sécurité avant de démarrer.",
      translation: "Buckle your seatbelt before starting.",
      nativeWord: "seatbelt",
      hint: "noun, feminine",
      wordType: "noun",
    },
    {
      id: "road-03",
      targetWord: "priorité",
      sentence: "Il faut donner la ____ aux piétons.",
      translation: "You must give priority to pedestrians.",
      nativeWord: "priority",
      hint: "noun, feminine",
      wordType: "noun",
    },
    {
      id: "road-04",
      targetWord: "vitesse",
      sentence: "La limitation de ____ est de 50 km/h en ville.",
      translation: "The speed limit is 50 km/h in town.",
      nativeWord: "speed",
      hint: "noun, feminine",
      wordType: "noun",
    },
    {
      id: "road-05",
      targetWord: "klaxonner",
      sentence: "Il ne faut pas ____ inutilement en ville.",
      translation: "You should not honk unnecessarily in the city.",
      nativeWord: "honk",
      hint: "verb, infinitive",
      wordType: "verb",
    },
    {
      id: "road-06",
      targetWord: "feux",
      sentence: "Marque l'arrêt au ____ rouge.",
      translation: "Stop at the red traffic light.",
      nativeWord: "traffic lights",
      hint: "noun, masculine plural",
      wordType: "noun",
    },
    {
      id: "road-07",
      targetWord: "croisement",
      sentence: "Ralentis avant le ____.",
      translation: "Slow down before the intersection.",
      nativeWord: "intersection",
      hint: "noun, masculine",
      wordType: "noun",
    },
    {
      id: "road-08",
      targetWord: "rétroviseur",
      sentence: "Vérifie ton ____ avant de changer de voie.",
      translation: "Check your mirror before changing lanes.",
      nativeWord: "mirror",
      hint: "noun, masculine",
      wordType: "noun",
    },
    {
      id: "road-09",
      targetWord: "dépasser",
      sentence: "Il est interdit de ____ sur une ligne continue.",
      translation: "It is forbidden to overtake on a solid line.",
      nativeWord: "overtake",
      hint: "verb, infinitive",
      wordType: "verb",
    },
    {
      id: "road-10",
      targetWord: "giratoire",
      sentence: "Cède le passage dans le sens du rond-point ____.",
      translation: "Give way in the direction of the roundabout.",
      nativeWord: "roundabout",
      hint: "adjective / noun, masculine",
      wordType: "adjective",
    },
  ],
};
